export const Summary_Table = "balances_Summary_Table";
export const Signals_Table = "balances_Signals_Table";

export const FETCH_BALANCES_BEGIN = "FETCH_BALANCES_BEGIN";
export const FETCH_BALANCES_SUCCESS = "FETCH_BALANCES_SUCCESS";
export const FETCH_BALANCES_FAILURE = "FETCH_BALANCES_FAILURE";

export const FETCH_CHART_DATA_BEGIN = "FETCH_CHART_DATA_BEGIN";
export const FETCH_CHART_DATA_SUCCESS = "FETCH_CHART_DATA_SUCCESS";
export const FETCH_CHART_DATA_FAILURE = "FETCH_CHART_DATA_FAILURE";

export const FETCH_TRANSACTION_DATA_BEGIN = "FETCH_TRANSACTION_DATA_BEGIN";
export const FETCH_TRANSACTION_DATA_SUCCESS = "FETCH_TRANSACTION_DATA_SUCCESS";
export const FETCH_TRANSACTION_DATA_FAILURE = "FETCH_TRANSACTION_DATA_FAILURE";
